# Generated by Django 5.0.6 on 2026-07-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendor', 'Vendeur'), ('customer', 'Client')], default='customer', max_length=20),
        ),
    ]
