# Generated by Django 5.0.6 on 2026-08-15 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_email_verified_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendor', 'Vendeur'), ('cashier', 'Caissier'), ('customer', 'Client')], default='customer', max_length=20),
        ),
    ]
