# Generated by Django 5.0.6 on 2026-07-25 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_image', models.ImageField(upload_to='sourcing/')),
                ('source_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle demande'), ('under_review', "En cours d'étude"), ('quoted', 'Devis envoyé'), ('converted', 'Convertie en commande'), ('rejected', 'Refusée')], default='new', max_length=20)),
                ('quoted_price_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_request', to='orders.order')),
            ],
            options={
                'db_table': 'sourcing_requests',
            },
        ),
    ]
