# Generated by Django 5.0.6 on 2026-07-25 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sourcingrequest',
            index=models.Index(fields=['status'], name='sourcing_re_status_b87096_idx'),
        ),
    ]
