# Generated by Django 5.0.6 on 2026-07-25 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='budget_max_xaf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='category',
            field=models.CharField(choices=[('bags', 'Sacs'), ('shoes', 'Chaussures'), ('clothing', 'Vêtements'), ('perfumes', 'Parfums'), ('watches', 'Montres'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='size_or_shoe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='reference_image',
            field=models.ImageField(blank=True, upload_to='sourcing/'),
        ),
    ]
