# Generated by Django 5.0.6 on 2026-07-25 00:19

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending_deposit', "En attente de paiement de l'acompte"), ('deposit_paid', 'Acompte reçu - Commande validée'), ('in_transit', "En cours d'acheminement Europe -> Cameroun"), ('ready_for_delivery', 'Arrivé au Cameroun - Prêt pour livraison'), ('completed', 'Solde payé + Colis livré'), ('cancelled', 'Annulé / Expiré')], default='pending_deposit', max_length=30)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('subtotal_xaf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_xaf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_xaf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deposit_percentage', models.PositiveSmallIntegerField(choices=[(50, 'Acompte 50%'), (70, 'Acompte 70%'), (100, 'Paiement intégral 100%')], default=50)),
                ('amount_paid_xaf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('shipping_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=64)),
                ('unit_price_xaf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
