# Generated by Django 5.0.6 on 2026-07-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('card', 'Carte bancaire')], max_length=20),
        ),
    ]
