# Generated by Django 5.0.6 on 2026-07-25 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_deposit', "En attente d'acompte"), ('deposit_paid', 'Acompte payé & Commande validée'), ('sourcing_in_progress', 'Achat en cours en Europe (Paris / Milan / Londres)'), ('shipped_from_europe', "Expédié depuis l'Europe"), ('arrived_in_cameroon', 'Disponible en agence au Cameroun'), ('delivered_and_completed', 'Livré au client & Solde réglé'), ('cancelled', 'Annulé / Expiré')], max_length=30)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'order status history',
                'db_table': 'order_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_notes',
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_notes',
            field=models.TextField(blank=True, help_text="Ex. « Colis dédouané à l'aéroport de Douala »."),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_deposit', "En attente d'acompte"), ('deposit_paid', 'Acompte payé & Commande validée'), ('sourcing_in_progress', 'Achat en cours en Europe (Paris / Milan / Londres)'), ('shipped_from_europe', "Expédié depuis l'Europe"), ('arrived_in_cameroon', 'Disponible en agence au Cameroun'), ('delivered_and_completed', 'Livré au client & Solde réglé'), ('cancelled', 'Annulé / Expiré')], default='pending_deposit', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_trackin_cd5d94_idx'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order'),
        ),
    ]
