# Generated by Django 5.0.6 on 2026-08-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderstatushistory_remove_order_tracking_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('shipped', 'Expédié')], default='pending', max_length=20),
        ),
    ]
