# Generated by Django 5.0.6 on 2026-08-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_fulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('card', 'Carte bancaire'), ('cash', 'Espèces')], max_length=20),
        ),
    ]
