# Generated by Django 5.0.6 on 2026-07-25 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('cinetpay', 'CinetPay'), ('flutterwave', 'Flutterwave'), ('cash_on_delivery', 'Espèces à la livraison'), ('momo_on_delivery', 'Mobile Money à la livraison')], max_length=30)),
                ('purpose', models.CharField(choices=[('deposit', 'Acompte'), ('balance', 'Solde restant'), ('full', 'Paiement intégral')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('amount_xaf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_reference', models.CharField(max_length=120, unique=True)),
                ('payer_phone_number', models.CharField(blank=True, max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['provider_reference'], name='transaction_provide_bae6ef_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx')],
            },
        ),
    ]
