# Generated by Django 5.0.6 on 2026-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('cinetpay', 'CinetPay'), ('flutterwave', 'Flutterwave'), ('cash_on_delivery', 'Espèces à la livraison'), ('momo_on_delivery', 'Mobile Money à la livraison'), ('sandbox', 'Bac à sable (démo, sans clés API réelles)')], max_length=30),
        ),
    ]
