# Generated by Django 5.0.6 on 2026-07-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_deposit_percentage',
            field=models.IntegerField(choices=[(50, '50%'), (70, '70%')], default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bags', 'Sacs'), ('shoes', 'Chaussures'), ('clothing', 'Vêtements'), ('perfumes', 'Parfums'), ('watches', 'Montres')], max_length=20),
        ),
    ]
