# Generated by Django 5.0.6 on 2026-07-25 18:20

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_default_deposit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload_to),
        ),
    ]
